#!/bin/bash
# Mise à jour des pixbuf loaders pour ajouter le support SVG à GTK2
/usr/bin/gtk-query-immodules-2.0 > /etc/gtk-2.0/gtk.immodules
/usr/bin/gdk-pixbuf-query-loaders > /etc/gtk-2.0/gdk-pixbuf.loaders
