#!/bin/sh
if [ ! -e /etc/xml/catalog ]

then

	echo "/etc/xml/catalog n'existe pas! Veuillez installer docbook-xml et exécuter à nouveau le script post-install!"
	exit 1
fi
if [ ! -d /etc/xml ]; then install -v -m755 -d /etc/xml; fi
if [ ! -f /etc/xml/catalog ]; then
    xmlcatalog --noout --create /etc/xml/catalog
fi

DBXSLVER=1.75.2
xmlcatalog --noout --add "rewriteSystem" \
	"http://docbook.sourceforge.net/release/xsl/$DBXSLVER" \
	"file:///usr/share/xml/docbook/xsl-stylesheets-$DBXSLVER" \
	/etc/xml/catalog
xmlcatalog --noout --add "rewriteURI" \
	"http://docbook.sourceforge.net/release/xsl/$DBXSLVER" \
	"file:///usr/share/xml/docbook/xsl-stylesheets-$DBXSLVER" \
	/etc/xml/catalog
xmlcatalog --noout --add "rewriteSystem" \
	"http://docbook.sourceforge.net/release/xsl/current" \
	"file:///usr/share/xml/docbook/xsl-stylesheets-$DBXSLVER" \
	/etc/xml/catalog
xmlcatalog --noout --add "rewriteURI" \
	"http://docbook.sourceforge.net/release/xsl/current" \
	"file:///usr/share/xml/docbook/xsl-stylesheets-$DBXSLVER" \
	/etc/xml/catalog
