#!/bin/sh
# Begin $rc_base/init.d/avahid

# Based on sysklogd script from LFS-3.1 and earlier.
# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org
# Add create user and Groups - thierryn1@hispeed.ch

# $Id: $

. /etc/sysconfig/rc
. $rc_functions
newgroup=avahi
newuser=avahi
newid=85
getent group $newgroup > /dev/null || /usr/sbin/groupadd -g $newid $newgroup
getent passwd $newuser > /dev/null || /usr/sbin/useradd -g $newgroup \
-u $newid -s /bin/false -c "Avahi Daemon" $newuser


case "$1" in
    start)
        boot_mesg "Starting Avahi Daemon..."
        loadproc /usr/sbin/avahi-daemon -D
        ;;

    stop)
        boot_mesg "Stopping Avahi Daemon..."
        killproc /usr/sbin/avahi-daemon
        ;;

    restart)
        $0 stop
        sleep 1
        $0 start
        ;;

    status)
        statusproc /usr/sbin/avahi-daemon
        ;;

    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

# End $rc_base/init.d/avahid
