#!/bin/sh

port=gnome-panel

# gconf schemas
SCHEMAS="`pkginfo -l $port | grep etc/gconf/schemas/.*\.schemas$`"

for SCHEMA in $SCHEMAS
do
	export GCONF_CONFIG_SOURCE=`gconftool-2 --get-default-source`
	gconftool-2 --makefile-install-rule /$SCHEMA > /dev/null
done

# gconf entries
ENTRIES="`pkginfo -l $port | grep etc/gconf/schemas/.*\.entries$`"

while [ ! -z "`pidof gconfd-2`" ]
do
	killall -q gconfd-2
	sleep 5
done

for ENTRY in $ENTRIES
do
	export GCONF_CONFIG_SOURCE=`gconftool-2 --get-default-source`
	gconftool-2 --direct --config-source $GCONF_CONFIG_SOURCE --load /$ENTRY > /dev/null
done

# reload gconf caches
if [ ! -z "`pidof gconfd-2`" ]
then
	killall -HUP gconfd-2 > /dev/null
fi

# scrolls
SCROLLS="`pkginfo -l $port | grep usr/share/omf/.*\.omf$`"

for SCROLL in $SCROLLS
do
	scrollkeeper-install -q -p /var/lib/scrollkeeper /$SCROLL > /dev/null
done

# End of file
