#!/bin/sh
# Begin $rc_base/init.d/wicd

# Based on sysklogd script from LFS-3.1 and earlier.
# Rewritten by thierryn1@hispeed.ch

. /etc/sysconfig/rc
. $rc_functions

case "$1" in
	start)
		boot_mesg "Starting the wicd Daemon..."
		loadproc /usr/share/wicd/daemon/wicd-daemon.py
		;;

	stop)
		boot_mesg "Stopping the wicd Daemon..."
		killproc /usr/share/wicd/daemon/wicd-daemon.py
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	status)
		statusproc /usr/share/wicd/daemon/wicd-daemon.py
		;;

	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 1
		;;
esac

# End $rc_base/init.d/wicd
