--- Makefile.orig	2008-10-02 10:33:21.000000000 +0200
+++ Makefile	2008-10-02 10:39:30.000000000 +0200
@@ -39,7 +39,7 @@ BTARGET  = version.gen version.h version
 BOBJECTS = $(BTARGET) \
 	mbr/mbr.bin mbr/gptmbr.bin \
 	core/pxelinux.0 core/isolinux.bin core/isolinux-debug.bin \
-	gpxe/gpxelinux.0 dos/syslinux.com win32/syslinux.exe \
+	gpxe/gpxelinux.0 dos/syslinux.com \
 	$(MODULES)
 
 # BSUBDIRs build the on-target binary components.
@@ -49,7 +49,7 @@ BOBJECTS = $(BTARGET) \
 # files that depend only on the B phase, but may have to be regenerated
 # for "make installer".
 BSUBDIRS = codepage core memdisk modules com32 mbr memdump gpxe sample \
-	   libinstaller dos win32
+	   libinstaller dos
 ITARGET  =
 IOBJECTS = $(ITARGET) dos/copybs.com \
 	utils/gethostip utils/isohybrid utils/mkdiskimage \
@@ -57,27 +57,17 @@ IOBJECTS = $(ITARGET) dos/copybs.com \
 ISUBDIRS = libinstaller mtools linux extlinux utils
 
 # Things to install in /usr/bin
-INSTALL_BIN   =	mtools/syslinux
-# Things to install in /sbin
-INSTALL_SBIN  = extlinux/extlinux
+INSTALL_BIN   =	mtools/syslinux extlinux/extlinux
 # Things to install in /usr/lib/syslinux
 INSTALL_AUX   =	core/pxelinux.0 gpxe/gpxelinux.0 core/isolinux.bin \
 		core/isolinux-debug.bin \
-		dos/syslinux.com dos/copybs.com win32/syslinux.exe \
+		dos/syslinux.com dos/copybs.com \
 		mbr/mbr.bin mbr/gptmbr.bin \
-		$(MODULES)
-INSTALL_AUX_OPT = win32/syslinux.exe
+		com32/menu/*.c32 com32/modules/*.c32
 
 # These directories manage their own installables
 INSTALLSUBDIRS = com32 utils
 
-# Things to install in /boot/extlinux
-EXTBOOTINSTALL = $(MODULES)
-
-# Things to install in /tftpboot
-NETINSTALLABLE = core/pxelinux.0 gpxe/gpxelinux.0 \
-		 $(MODULES)
-
 all:
 	$(MAKE) all-local
 	set -e ; for i in $(BSUBDIRS) $(ISUBDIRS) ; do $(MAKE) -C $$i $@ ; done
@@ -102,11 +92,8 @@ version.mk: version version.pl
 local-install: installer
 	mkdir -m 755 -p $(INSTALLROOT)$(BINDIR)
 	install -m 755 -c $(INSTALL_BIN) $(INSTALLROOT)$(BINDIR)
-	mkdir -m 755 -p $(INSTALLROOT)$(SBINDIR)
-	install -m 755 -c $(INSTALL_SBIN) $(INSTALLROOT)$(SBINDIR)
 	mkdir -m 755 -p $(INSTALLROOT)$(AUXDIR)
 	install -m 644 -c $(INSTALL_AUX) $(INSTALLROOT)$(AUXDIR)
-	-install -m 644 -c $(INSTALL_AUX_OPT) $(INSTALLROOT)$(AUXDIR)
 	mkdir -m 755 -p $(INSTALLROOT)$(MANDIR)/man1
 	install -m 644 -c man/*.1 $(INSTALLROOT)$(MANDIR)/man1
 	: mkdir -m 755 -p $(INSTALLROOT)$(MANDIR)/man8
@@ -115,15 +102,7 @@ local-install: installer
 install: local-install
 	set -e ; for i in $(INSTALLSUBDIRS) ; do $(MAKE) -C $$i $@ ; done
 
-netinstall: installer
-	mkdir -p $(INSTALLROOT)$(TFTPBOOT)
-	install -m 644 $(NETINSTALLABLE) $(INSTALLROOT)$(TFTPBOOT)
-
-extbootinstall: installer
-	mkdir -m 755 -p $(INSTALLROOT)$(EXTLINUXDIR)
-	install -m 644 $(EXTBOOTINSTALL) $(INSTALLROOT)$(EXTLINUXDIR)
-
-install-all: install netinstall extbootinstall
+install-all: install
 
 local-tidy:
 	rm -f *.o *.elf *_bin.c stupid.* patch.offset

