#!/bin/sh

port=gnome-desktop

# scrolls
SCROLLS="`pkginfo -l $port | grep usr/share/omf/.*\.omf$`"

for SCROLL in $SCROLLS
do
	/usr/bin/scrollkeeper-install -q -p /var/lib/scrollkeeper /$SCROLL > /dev/null
done

# End of file
