#!/bin/sh
# Mettre a jour les modules
depmod

# Si pas de groupe vboxusers on en creer un
/usr/bin/getent group vboxusers || /usr/sbin/groupadd -g 80 vboxusers

# Ajout du module dans /etc/sysconfig/modules
if ! grep "vboxdrv" /etc/sysconfig/modules >/dev/null; then
        sed -i '/End/ i vboxdrv' /etc/sysconfig/modules
fi
if ! grep "vboxnetflt" /etc/sysconfig/modules >/dev/null; then
        sed -i '/End/ i vboxnetflt' /etc/sysconfig/modules
fi


# End of File

